config/routes.rb
Rails3MongoidDevise::Application.routes.draw do
  resources :products
  root to: 'products#index'
end

app/models/product.rb
class Product
  include Mongoid::Document

  field :name, type: String
  field :price, type: Integer

  validates :name, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  respond_to :html, :json

  private
  def set_flash_message(message, type)
    flash[type.to_sym] = message
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = get_product params[:id]
  end

  def new
    @product = Product.new
  end

  def edit
    @product = get_product params[:id]
  end

  def create
    @product = Product.new params[:product]
    set_flash_message 'Product was successfully created.','notice' if Creation.perform_async params[:product]
    respond_with @product
  end

  def update
    @product = get_product params[:id]
    set_flash_message 'Product was successfully updated.','notice' if UpdateProduct.perform_async params[:id], params[:product]
    respond_with @product
  end

  def destroy
    @product = get_product params[:id]
    set_flash_message 'Product was successfully deleted.','notice' if @product.destroy
    respond_with @product
  end

  private
  def get_product id
    Product.find id rescue redirect_to root_path, alert: "Not found."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3MongoidDevise</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>

<br/>

<p id="notice"><%= notice %></p>
<p id="error" style="color:red;"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |t| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= t.label :name %><br />
    <%= t.text_field :name %>
  </div>
  <div class="field">
    <%= t.label :price %><br />
    <%= t.number_field :price %>
  </div>
  <div class="actions">
    <%= t.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing todolist</h1>

<%= render 'form' %>

<%= link_to 'Show', product_path(@product) %>|
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>name</th>
    <th>User</th>
    <th>price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.price %></td>

    <td><%= link_to 'Show', product_path(product) %></td>
    <td><%= link_to 'Edit', product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
    
<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <b>name:</b>
  <%= @product.name %>
</p>

<p>
  <b>price:</b>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>